### ISSUE TITLE
Bug with id constraint

### ISSUE THREAD

**Issue by evcastelani** [fsobral/pack-u#8]
The id constraint must be respect if there is an id element. For example, we can't allocate  items with id=0 in a container with id=1 without an item with id=1.

**Comment by fsobral** [comment]
Of course. I forgot this requirement. Maybe we should change
`getAvaialableContainers`. Any other ideas?

Please, put your failed test in our pool of tests!

**Comment by fsobral** [comment]
I think I've fixed the problem.

**Comment by evcastelani** [comment]
I don't know...In my opnion the bug persists. Have you been tried the example t1?

**Comment by fsobral** [comment]
Ok. Now I think it is fixed.

**Comment by fsobral** [comment]
I've ran example `t1` and the output was as expected to me. I think that there is something wrong with the `true_sol.txt`. Maybe you have changed the order of items after building it?

    True Solution        My solution

    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 64, 0, 0,         2,   40,    0,    0,
    2, 0, 40, 0,         2,   40,    0,    0,
    2, 0, 40, 0,         2,   40,    0,    0,
    2, 0, 40, 0,         2,   40,    0,    0,
    2, 0, 40, 0,         2,   40,    0,    0,
    3, 0, 0, 50,         2,    0,   64,    0,
    3, 0, 0, 50,         2,    0,   64,    0,
    3, 0, 0, 50,         3,    0,    0,   50,
    3, 0, 0, 50,         3,    0,    0,   50,
    3, 0, 0, 50,         3,    0,    0,   50,
                         3,    0,    0,   50,
                         3,    0,    0,   50,
                         2,    8,   32,    0,

**Comment by evcastelani** [comment]
Yes, you right, let me post the new (correct) t1 example.

**Comment by evcastelani** [comment]
Done! Everything seems fine to me. I will try other examples.

**Comment by evcastelani** [comment]
I create more examples. They are very simple, but in all tests packu find the same solution! :)
